// This file is automatically generated

using SolastaModApi.Diagnostics;
using SolastaTesting.SolastaModApi;
using System;

namespace SolastaModApi
{
    /// <summary>
    /// Helpers for retrieving definitions we created
    /// </summary>
    public static class DbHelpers
    {
        public static TDb Get<TDb>(string name, string guid, bool throwIfNotFound = false) where TDb : BaseDefinition
        {
            var db = DatabaseRepository.GetDatabase<TDb>();
            Assert.IsNotNull(db, $"Database '{typeof(TDb).Name}' not found.");

            var definition = db.TryGetElement(name, guid);

            if (throwIfNotFound && definition == null)
                throw new SolastaModApiException(
                    $"The definition with name '{definition.name}' and guid '{guid}' could not be found in database '{typeof(TDb).Name}'");


            return definition;
        }

        public static TDb Get<TDb>(string name, Guid guidNamespace, bool throwIfNotFound = false) where TDb : BaseDefinition
        {
            return Get<TDb>(name, GuidHelper.Create(guidNamespace, name).ToString("N"), throwIfNotFound);
        }
    }
}

